[package]
name = "burn_test"
version = "0.1.0"
edition = "2024"

include = [
    "src/main.cpp",
    "src/main.hpp",
    "src/main.h",
    "src/main.rs",
    "Cargo.toml",
    "Makefile",
    "build.rs",
    "compile.py",
]

[[bin]]
name = "infer-server"
path = "src/main.rs"

[dependencies]
image = { version = "0.25.6", features = ["serde", "nasm"] }
